apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - name: uimport
          containerPort: 15672
        - name: mport
          containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - name: uimport
    port: 15672
    targetPort: 15672
  - name: mport
    port: 5672
    targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-cluster
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672




